#!/bin/bash

aclocal -I m4 && \
    autoheader && \
        libtoolize --copy --force && \
            autoconf && \
                automake --add-missing --copy

status=$?

if [ $status == 0 ]; then
    if [ "$1" == "configure" ]; then
        shift
        ./configure $*
        status=$?
    fi
fi

exit $status
