#ifndef __MURPHY_CONSOLE_PROTOCOL_H__
#define __MURPHY_CONSOLE_PROTOCOL_H__

#define MRP_CONSOLE_INPUT  0x1
#define MRP_CONSOLE_OUTPUT 0x2
#define MRP_CONSOLE_PROMPT 0x3
#define MRP_CONSOLE_BYE    0x4


#endif /* __MURPHY_CONSOLE_PROTOCOL_H__ */
